version: "3.3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_CLIENT_SECRET=${REACT_APP_CLIENT_SECRET}
      - REACT_APP_GITLAB_APP_ID=${REACT_APP_GITLAB_APP_ID}
      - REACT_APP_GITLAB_APP_SECRET=${REACT_APP_GITLAB_SECRET}
      - REACT_APP_GITLAB_REDIRECT_URI=${REACT_APP_GITLAB_REDIRECT_URI}