version: "3.3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_CLIENT_SECRET=${REACT_APP_CLIENT_SECRET}
